export interface QuestTemplate {
  hooks: string[];
  objectives: string[];
  pressures: string[];
  twists: string[];
}

export const questPool: QuestTemplate = {
  hooks: [
    "A stablehand is frozen in a 'T-Pose'; the horses nearby are speaking in binary code.",
    "The sky 'peels' back in giant gray squares, revealing a void of scrolling green script.",
    "A local merchant 'lags', physically snapping back to the same spot every five seconds.",
    "The town well starts pouring out liquid static that 'deletes' any bucket lowered into it.",
    "A frantic knight arrives with his armor 'clipping' through his body, screaming about a 'Hard Reset'.",
    "Every candle in the tavern flickers purple; the patrons' shadows detach and start 'defragmenting'.",
    "A 'Missing Texture' void opens in the town square, swallowing all color and sound within 30ft.",
    "A messenger delivers a scroll that is blank, save for a '404: DESTINY_NOT_FOUND' error in gold ink.",
    "The village children are found 'floating' three feet off the ground, stuck in a 'Gravity Loop'.",
    "Static fills the air as the local temple's bells start ringing a high-pitched 'System Alert' chime.",
  ],
  objectives: [
    "Locate the 'World Seed' at the center of the forest and manually reboot the local physics engine.",
    "Hunt down a 'Corrupted Sprite'—a monster that is eating the NPC metadata of the village elders.",
    "Shatter the 'Ever-Wailing' anchor before its audio-loop resonance collapses the party's eardrums.",
    "Retrieve a 'Backup Artifact' from a dungeon that is currently 'formatting' itself into nothingness.",
    "Navigate to the 'Edge of the Map' to patch a reality rift that is leaking unrefined mana-code.",
    "Extract an ancient Sphinx—a 'System Admin'—trapped in a recursive logic loop of its own riddles.",
    "Identify and 'Delete' the source of a Void Virus that is overwriting the memories of the local guard.",
    "Escort a 'Glitch-Cat' through the mountains to the world's 'Control Panel' to reset the weather.",
    "Find the 'Source Code' of a dying deity before it is permanently overwritten by a legacy bug.",
    "Seal a 'Reality Leak' in the cemetery before the 'Ghost-Tide' can overwrite the souls of the living.",
  ],
  pressures: [
    "The 'Blue Screen of Death' is sweeping the horizon, erasing every asset it touches.",
    "Reality's 'Frame Rate' is dropping; if it hits 0fps, the entire plane freezes forever.",
    "The 'Garbage Collector' entity is arriving in 2 hours to purge all 'unauthorized' lifeforms.",
    "A countdown timer is burning into the party's retinas, ticking toward a 'Global Wipe'.",
    "Memory usage is at 99%; if it hits 100, the party's unique identities will be 'Compressed'.",
    "The tavern is surrounded by an impenetrable mist that is 'downscaling' in size every 10 minutes.",
    "The party has been hit with a 'Latency Curse'; their actions are now delayed by 3 seconds.",
    "A 'Critical World Update' is scheduled for midnight; anyone outside a 'Safe Zone' will be reset.",
    "The 'Save File' for this region is corrupted; you must finish before the next auto-save attempt.",
    "The sun is flickering out like a dying monitor; total 'System Darkness' is imminent.",
  ],
  twists: [
    "The 'Villain' was actually an anti-virus guardian trying to quarantine the party.",
    "The party realizes they are 'Legacy Code' from a world that was supposed to be deleted eons ago.",
    "The quest giver is a 'Logic Bug' that used the party to bypass the world's internal firewalls.",
    "The 'Relic' you saved is a sentient 'Format' bomb designed to wipe the entire city's history.",
    "Success triggers a 'System Restore', meaning the world resets and no one remembers your help.",
    "The 'NPCs' in the village are just 'Low-Res' illusions generated by the monster you're hunting.",
    "The real threat isn't the monster, but the 'Admin' who is trying to delete this 'Broken' world.",
    "The party realizes they are 'Duplicate Assets' of heroes who already failed this quest once.",
    "The enemy cannot be killed by swords, only 'commented out' by solving a syntax riddle.",
    "The entire world is a simulation running inside a larger, much more 'Cursed' Bag of Holding.",
  ],
};
